[package]
name = "wowza-rest-rust"
version = "0.0.0"
authors = ["nikos efthias <nikos@mugsoft.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
